### ISSUE TITLE
is there a tutorial ? I get the following message. how to configure it ?

### ISSUE THREAD

**Issue by xvusrmqj** [tomi/vscode-rf-language-server#7]
Message: Request textDocument/completion failed with message: Cannot read property 'fileTree' of undefined  Code: -32603

**Comment by tomi** [comment]
Hi. For basic use there's not really any need for configuration. You just open a `.robot` file and should be good to go. Could you provide the steps to reproduce the error you got? I.e. the command you did and on what file.

**Comment by xvusrmqj** [comment]
just input anything. then get the error message.  below is the screent shot.
![image](https://user-images.githubusercontent.com/2316516/28549582-9f4c458a-710d-11e7-87a7-3beca8379e35.png)

**Comment by tomi** [comment]
Seems the extension didn't work that well opening a single file instead of a folder. That should be fixed in the newly released 0.8.1 version.

The extension itself doesn't necessarily require any configuration. You can see the supported features in the [README.md](https://github.com/tomi/vscode-rf-language-server/blob/master/client/README.md). If you're looking for how to use Robot Framework, you can check its website [here](http://robotframework.org).
